[WebService]
AllowUnencrypted = true
LoginTo = false
ProtocolHeader = X-Forwarded-Proto
Origins = https://<GATEWAY_DOMAIN>
UrlRoot = /cockpit/

[bearer]
command = /usr/local/bin/cockpit-bearer-auth
timeout = 300

[Session]
IdleTimeout = 30
