FROM quay.io/cockpit/ws:latest

RUN dnf install -y --setopt=install_weak_deps=False \
    cockpit-bridge \
    cockpit-networkmanager \
    cockpit-podman \
    cockpit-storaged \
    cockpit-system \
    podman \
    && dnf clean all

CMD ["/bin/sh", "-c", "printf '[WebService]\nAllowUnencrypted = true\nLoginTo = false\nProtocolHeader = X-Forwarded-Proto\nOrigins = https://%s\nUrlRoot = /cockpit/\n' \"${GATEWAY_DOMAIN:?GATEWAY_DOMAIN is required}\" > /etc/cockpit/cockpit.conf && exec /usr/libexec/cockpit-ws --no-tls --local-session /usr/bin/cockpit-bridge"]
