FROM quay.io/cockpit/ws:latest

RUN dnf install -y --setopt=install_weak_deps=False \
    cockpit-bridge \
    cockpit-networkmanager \
    cockpit-podman \
    cockpit-storaged \
    cockpit-system \
    podman \
    && dnf clean all

CMD ["/usr/libexec/cockpit-ws", "--no-tls", "--local-session", "/usr/bin/cockpit-bridge"]
