[book]
title = "AtomixOS"
description = "Secure, reproducible appliance OS with atomic updates and rollback"
authors = ["Robert DeRose"]
language = "en"
src = "src"

[build]
build-dir = "../book"
create-missing = false

[preprocessor.mermaid]
command = "mdbook-mermaid"

[output.html]
default-theme = "navy"
preferred-dark-theme = "navy"
git-repository-url = "https://github.com/RobertDeRose/atomixos"
edit-url-template = "https://github.com/RobertDeRose/atomixos/edit/dev/docs/src/{path}"
additional-css = ["theme/cobalt.css"]
additional-js = ["mermaid.min.js", "mermaid-init.js"]
